# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='last_num',
            field=models.IntegerField(),
        ),
    ]
