# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usermodel_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='ticket',
        ),
    ]
